### ISSUE TITLE
Keyring does not autodetect and use backend when used in PyInstaller

### ISSUE THREAD

**Issue by nreker** [jaraco/keyring#399] opened 2019-09-11 22:06 UTC
Keyring does not autodetect and use backend when used in PyInstaller

**To Reproduce**
_test.py:_
import keyring
keyring.set_password("system", "username", "password")
print( keyring.get_password("system", "username") )

$ pyinstaller test.py
...
$ ./dist/test/test 
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    keyring.set_password("app","appuser","password")
  File "site-packages/keyring/core.py", line 61, in set_password
  File "site-packages/keyring/backends/fail.py", line 24, in get_password
RuntimeError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[15741] Failed to execute script test

$ PYTHON_KEYRING_BACKEND=keyring.backends.OS_X.Keyring ./dist/test/test 
password

**Expected behavior**
$ ./dist/test/test 
password

**Environment**
```
Python		3.7.2
keyring		19.1.0   
PyInstaller	3.5  
MacOS           10.14.6 

keyring.backends.fail.Keyring (priority: 0)
keyring.backends.OS_X.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 0)
```

**Additional context**
I realize this may be about how to configure PyInstaller but not sure where to start.

**Comment by jaraco** [comment] 2019-12-24 15:22
This is a duplicate of #324.

**Closed as completed by jaraco** 2019-12-24 15:22 UTC
Labels: duplicate

**Comment by AndreyNikiforov** [comment] 2023-01-29 18:28
[solved](https://github.com/AndreyNikiforov/keyring_test) same/similar issue by using `pyinstaller --collect-all keyrings.alt --hidden-import pkgutil`
