### ISSUE TITLE
Keyrings unavailable on pyinstaller

### ISSUE THREAD

**Issue by c-rei** [jaraco/keyring#324] opened 2018-05-09 23:42 UTC
This error appears when I updated keyring from version 11.0.0 to version 12.2.0 and compiled my source with the pyinstaller. The source file works fine, However on running the binary I get `RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.`

I have installed keyrings.alt, but I don't known how to use it, and how to modify my source for keyring.

Thank for any help.

**Comment by jaraco** [comment] 2018-05-10 08:48
You'll notice in the changelog that [starting with version 12 of keyring](https://keyring.readthedocs.io/en/latest/history.html), it now relies on entry points to discover keyring backends. My suspicion is that something about pyinstaller breaks the metadata, rendering the backends invisible.

I think you have three options.

1. Stick with `keyring<12`.
2. In your application, explicitly import the keyring backend modules and re-initialize the keyring. Perhaps keyring could supply this functionality as a call for pyinstaller-based applications.
3. Verify my suspicion and then ask pyinstaller to support discovery of entry points in their environment.

**Comment by c-rei** [comment] 2018-05-10 23:40
Thank you for your help.
I have investigated the keyring backend with get_keyring function, and that returned ~Windos.WinVaultKering while I on my source, but ~fail.Keyring while I on a binary. So I'v tried to set the "keyring.backends.Windows.WinVaultKeyring" with set_keyring function, but got an error "AttributeError: module 'keyring.backend' has no attribute 'Windows'".
I want to choice the option 2 that you advised, but I don't known how to re-initialize the keyring. Could you give me some idea?

**Comment by jaraco** [comment] 2018-05-10 23:58
I think you want to `import keyring.backends.Windows` in order for `keyring.backends.Windows.WinVaultKeyring` to be viable. Does that help?

**Comment by c-rei** [comment] 2018-05-11 00:50
It works now as you advised.
Thank you very much.

**Comment by genotrance** [comment] 2018-09-06 20:18
I just spent several hours struggling with PyInstaller and keyring. I think it is worthwhile for keyring to provide functionality to pick the correct backend by default once frozen like you suggested rather than have to hard code it.

**Comment by jaraco** [comment] 2019-12-24 15:34
I'm re-opening this issue, as it remains an issue (as reported in the duplicate issues). In #416, here's what I recommend:

`pyinstaller` should supply the metadata. Now that keyring is using [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), it should be able to follow the [instructions on extending the search algorithm](https://docs.python.org/3/library/importlib.metadata.html#extending-the-search-algorithm) to improve the discoverability of _all_ metadata (and not just entrypoints) for the packages it is assembling.

**Comment by jaraco** [comment] 2019-12-24 15:44
This work is proceeding in pyinstaller/pyinstaller#1188.

**Comment by c-rei** [comment] 2019-12-24 23:57
Mr. jaraco

Thank you for your information. I'll check it a later.

**Comment by c-rei** [comment] 2020-01-09 01:47
Mr. jaroco

I'v checked it. I tried to update keyring version from 18.0.0 to 20.0.0, and compiled my source with the pyinstaller. Then below error occurred.

```
  File "site-packages\keyring\core.py", line 192, in <module>
  File "site-packages\keyring\core.py", line 96, in init_backend
  File "site-packages\keyring\util\__init__.py", line 22, in wrapper
  File "site-packages\keyring\backend.py", line 216, in get_all_keyring
  File "site-packages\keyring\backend.py", line 199, in _load_plugins
KeyError: 'keyring.backends'
```

As your advise, I import keyring package like below,

```
if sys.platform == 'darwin':    # It's a solution for Mac
    import keyring.backends.OS_X
    keyring.set_keyring(keyring.backends.OS_X.Keyring())
else:   # It's a solution for Windows
    import keyring.backends.Windows
    keyring.set_keyring(keyring.backends.Windows.WinVaultKeyring())
```

It works with keyring 18.0.0, even though source or binary. So I must use old version.
Could you have any good ideas?

**Comment by ele3131** [comment] 2020-02-06 06:13
Same problem here! Downgrading to 18.0.0 makes it work (Thanks c-rei)

**Comment by jaraco** [comment] 2020-02-06 14:52
Could you determine the version of keyring in which it stops working? There were [several releases](https://keyring.readthedocs.io/en/latest/history.html) of keyring between 18.0.0 and 20.0.0.

**Comment by ele3131** [comment] 2020-02-06 19:28
It stopped working at 19.3.0, my error code:
```
Traceback (most recent call last):
  File "NovaPriceNotifier.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\miche\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\browser_cookie3\__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\miche\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\keyring\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\miche\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\keyring\core.py", line 192, in <module>
  File "site-packages\keyring\core.py", line 96, in init_backend
  File "site-packages\keyring\util\__init__.py", line 22, in wrapper
  File "site-packages\keyring\backend.py", line 216, in get_all_keyring
  File "site-packages\keyring\backend.py", line 199, in _load_plugins
KeyError: 'keyring.backends'
```

**Comment by jaraco** [comment] 2020-02-09 04:32
Okay, so the issue is almost certainly the switch to using [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) for resolving entry points, already discussed on Dec 24. My guess is that PyInstaller is relying on the [hook-keyring.backend.py](https://github.com/jaraco/keyring/blob/a9fe22750359c2ca337c83d838e3654ef1fa38ea/hook-keyring.backend.py) but that's failing. I just double-checked, and it does appear to be reporting the hidden modules:

```
keyring master $ python -i hook-keyring.backend.py
>>> hiddenimports
['keyring.backends.kwallet', 'keyring.backends.SecretService', 'keyring.backends.Windows', 'keyring.backends.chainer', 'keyring.backends.OS_X']
```

I think what you really want is to follow up in the aforementioned pyinstaller issue to ensure that pyinstaller supplies the necessary metadata. I don't think there's any more action that keyring can do here, so I'm going to close the issue, but don't hesitate to keep the conversation going, especially if you have questions that need answered or if there's something that keyring can do to accommodate PyInstaller (short of re-writing its plugin design).

**Closed as completed by jaraco** 2020-02-09 04:32 UTC

**Comment by 4rm** [comment] 2020-02-18 07:00
I'm having trouble using pyinstaller with a method mentioned above. I'm running Windows 10 64-bit.

I have downloaded keyring 18.0.0, and I am importing as
```
import keyring
from keyring.backends import Windows
keyring.set_keyring(Windows.WinVaultKeyring())
```

When I try to run my .exe, I'm getting 

`No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.`

I then tried installing `keyrings.alt` (3.4.0) and importing as
```
from keyrings.alt import Windows
keyring.set_keyring(Windows.RegistryKeyring())
```

but I still get the same error message as above. 

I ran the above tests using pyinstaller 4.0. When I try to run using pyinstaller 3.6, I get 
```
Traceback (most recent call last):
  File "C:\Users\Emilio\AppData\Local\Programs\Python\Python38\Lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
    import pkg_resources as res
  File "c:\users\emilio\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[1204] Failed to execute script pyi_rth_pkgres
```
Is there anything I can do? Should I use an even older version? Thanks for any help.

---

EDIT: I was able to get this working with the following:

Keyring 18.0.0
Python 3.8.1 64-bit
Pyinstaller 4.0.dev0+a1f92c6a08
```
import keyring
from keyring.backends import Windows
keyring.set_keyring(Windows.WinVaultKeyring())
```

and then in my .spec file, `hiddenimports=['win32timezone']`

**Comment by schlomo** [comment] 2020-07-01 19:13
On Windows & Mac I had to do this to get `keyring` work with `pyinstaller`:

```bash
pyinstaller \
    --noconfirm \
    --hidden-import win32ctypes.core.ctypes \
    --hidden-import win32ctypes.core.ctypes._common \
    --hidden-import win32ctypes.core.ctypes._dll \
    --hidden-import win32ctypes.core.ctypes._resource \
    --hidden-import win32ctypes.core.ctypes._system_information \
    --hidden-import win32ctypes.core.ctypes._time \
    --hidden-import win32ctypes.core.ctypes._authentication \
    myscript.py
```

and in the code I also had to manually initialize the `keyring` backend:

```python
system = platform.system()
if  system == 'Darwin':
    keyring.set_keyring(OS_X.Keyring())
elif system == 'Windows':
    keyring.set_keyring(Windows.WinVaultKeyring())
else:
    pass # rely on autodiscovery for other platforms
```

PyInstaller had to be taken from the develop git branch as the last release wouldn't work due to some other error.
All versions current as of today.

**Comment by rob99** [comment] 2020-09-03 05:08
Further to the list of --hidden-imports from @schlomo I had to add `win32cred` and `win32timezone`.

keyring v21.3.1
pyinstaller v3.6

**Comment by b-git-out** [comment] 2020-09-22 09:29
I solved by adding: 

```
from keyring.backends import Windows

keyring.set_keyring(Windows.WinVaultKeyring())
```

to my python file, and win32cred, win32timezone to my hidden imports as said by @rob99

**Comment by AndreyNikiforov** [comment] 2023-01-29 18:28
[solved](https://github.com/AndreyNikiforov/keyring_test) same/similar issue by using `pyinstaller --collect-all keyrings.alt --hidden-import pkgutil`
