### ISSUE TITLE
module not working on macOS?

### ISSUE THREAD

**Issue by 42sol-eu** [jaraco/keyring#268] opened 2017-03-19 05:05 UTC
Hi after installing with `pip3 install keyring` the access of the library crashes:

Wells:~ felix$ python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information

>>> keyring.set_password("AAA", "user", "password")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyring/backends/OS_X.py", line 35, in set_password
    api.set_generic_password(self.keychain, service, username, password)
NameError: name 'api' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyring/backends/OS_X.py", line 36, in set_password
    except api.Error:
NameError: name 'api' is not defined

**Comment by jaraco** [comment] 2017-03-19 12:47
This is a duplicate of #266, although now that another person has raised the issue, I believe there is an undeclared dependency on `six`. You should be able to work around the issue with a `pip3 install six`.

**Closed as completed by jaraco** 2017-03-19 12:47 UTC
Labels: duplicate
