### ISSUE TITLE
why so many releases?

### ISSUE THREAD

**Issue by prometheanfire** [jaraco/keyring#234] opened 2016-06-27 17:37 UTC
I package keyring for Gentoo and keeping it up to date is a chore.  There have been 3 releases in the last couple of days.  Is there a way to know what versions would be preferred to package?

**Comment by mitya57** [comment] 2016-06-27 20:15
FWIW, I'm packaging Keyring for Debian/Ubuntu, and the "release early, release often" strategy works fine for me.
If a release is not relevant for us (i.e. fixing an issue in Windows or OS X backends, or an issue specific to PyPI distribution), I ignore that release.

**Comment by jaraco** [comment] 2016-06-27 20:43
The reason keyring has so many releases is fourfold:
1. The release process has been simplified to a "tag & push" process, so it's so lightweight there's no intrinsic impediment to making releases.
2. As it's impossible to anticipate when the _next_ release is going to occur, it's difficult to withhold releases artificially. That is, a small change might come and seem unworthy of a release, but then might sit for several months awaiting another indication for a push. To avoid that, I prefer to publish releases as soon as they're ready.
3. Releasing early and often means that any suitably stable change can be released quickly and not be bundled with other changes, allowing for regressions to be detected and corrected more quickly, and often without intervening changes.
4. By releasing every version of the software, it's easy for anyone to bisect changes and adopt features without needing to check out the source code (simply using `pip install` for example).

It's very rare that I'll make a release knowing that another release is imminent. I generally only do that if I want to be sure to create a gap between deprecation of a feature and removal of the interface.

@prometheanfire I certainly don't want to create a hassle for you. If there's something that keyring can do to help automate the downstream release process and make it less of a chore, I'm happy to help support that. At the very least, I don't expect that downstream packages will necessarily adopt each release, but should follow whatever cadence works best for their environment and use case. Because Gentoo has access to every published release, it also has the control to select which releases to incorporate or not, but of course has the same problem I do -- not knowing whether the release yesterday will be followed by another contrib and release tomorrow.

I like @mitya57's guidance - incorporate relevant releases as resources permit and disregard the irrelevant ones. Consider delaying releases by a few weeks or making timed releases to limit the frequency of them. You have that control.

I hope that helps and gives some context. I hope that answers your questions, so I'll close this ticket, but don't hesitate to make suggestions or follow up with questions if there's any open concerns.

**Closed as completed by jaraco** 2016-06-27 20:43 UTC
Labels: question

**Comment by prometheanfire** [comment] 2016-06-27 21:02
It's not much of a hassle, was more curious as to why, we tend to package multiple releases and try to keep up to date, packaging it so often is just odd, this is the only project I package I do it with.  In general I've just been picking about one release a month to package and eventually make stable, that seems to work for pacing.  Thanks for the response :D
