### ISSUE TITLE
Client app backintime fails to pick correct keystore; client picks KWallet instead SecretStore

### ISSUE THREAD

**Issue by bentolor** [jaraco/keyring#391] opened 2019-06-11 13:33 UTC
I'm an end user coming from https://github.com/bit-team/backintime/issues/990

The actual application I want to use started to fail to store passwords due to being unable to find any appropriate keystore. 

My list of backends seems to be correct:

```
$ keyring --list-backends
keyring.backends.kwallet.DBusKeyring (priority: 4.9)
keyring.backends.kwallet.DBusKeyringKWallet4 (priority: 3.9)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 10)
```

Unfortunately when I try to access a keyring (`keyring get system username`), I get a KDE Wallet prompt to create a new wallet. As a plain Gnome Shell user with installed `seahorse` I'd expect my `gnome-keystore` to be the one-stop goto?!

#### My workaround
I created a `~/.local/share/python_keyring/keyringrc.cfg` with the following content:

```
[backend]
default-keyring=keyring.backends.SecretService.Keyring
```

Now the application seems to work. The `keyring get system username` directly returns without any prompt.

#### Expected behavior
I'd expect it should just work. But I'm unsure if the erratic behavior is in keyring which should stick to SecretService or in the code of backintime https://github.com/bit-team/backintime/blob/012d9783e966c6744ab30ce6abd299206a324473/common/tools.py#L796 which fails, because it cannot make sense of the `ChainerBackend`

Linus would say: Broken userspace ;-)

What fix is required where?

**Comment by jaraco** [comment] 2019-06-22 14:35
First, thank you for the thoughtful and meaningful report.

Looking at your backends and their priorities, everything looks right. It's surprising to me the behavior you describe. I'm guessing that the KDE Wallet prompt is somehow due to the kwallet.DBusKeyring getting selected.

After some pondering, I think I may understand what's going on.

The ChainerBackend is designed to enable multiple backends if viable to be used... and to scan all such backends for credentials. So, when you invoke `keyring.get_password()`, it goes to the highest priority backend (Chainer) and it [loops through the other backends](https://github.com/jaraco/keyring/blob/a65aa2ea949e78f67dc03abc4bfd4a691bdf0802/keyring/backends/chainer.py#L42). The SecretService keyring will be queried first, but if it's a miss (no password defined), the kwallet backend(s) will be queried, triggering the wallet creation UI.

The workaround you've created works by specifying the backend rather than letting the Chainer take precedence.

I believe the SecretService store is being queried first, but just not satisfying the operation.

Can you confirm that the `user` and `service` you're supplying would return `None` in the SecretService?

> What fix is required where?

In some ways, the behavior you describe is by design. But you've stumbled on a flaw in the design.

When I originally accepted the Chainer behavior, I was tempted to make it opt-in, but @zooba convinced me to make it enabled by default, providing a nice experience for environments where multiple backends are expected to be meaningful and valuable. Where a backend triggers blocking UI elements and [raises KeyringLocked exceptions](https://github.com/jaraco/keyring/blob/a65aa2ea949e78f67dc03abc4bfd4a691bdf0802/keyring/backends/kwallet.py#L101), however, that's not desirable.

Some of the current behaviors I wish to retain:

- Keyring should continue to detect all viable backends and select the best one for an environment.
- Keyring should continue to allow multiple backends to serve a query.

I can imagine a few ways to address the situation:

- Provide a mechanism in the environment to disable the chainer backend.
- Provide a mechanism by which backends can opt out of the chainer (such as those that trigger blocking UIs).
- Provide a mechanism to disable classes of backend such as kwallet.
- Update the interface to allow backends to suppress blocking behaviors and invoke this safer invocation when querying via the chainer.

@bentolor Does my description make sense? In light of this information, what's your instinct about what should be done?

**Comment by bentolor** [comment] 2019-06-22 18:52
Thank you very much @jaraco for your extensive answer. This clears a few things up.

If I understand you right, the `ChainerBackend` is a new feature which was not previously implemented. I guess it's core intention is to take the burden from the developer to find out the correct & viable key store. 

As far as I understand this is what currently the _Back-in_Time_ code does: It tries to go in a sensible way through each keystore types it knows of tries to access it on its own. Now the _Back-in_Time_ code is failing because it gets exposed to this "new" keystore `ChainerBackend` it never heard before.

So these are the problems I'm facing:
1. jaroco tells _Back-in-time_ to go with the `ChainerBackend` backend and the application has no clue how to tackle that one
2. During the discovery of sensible keystores, the `ChainerBackend` taints every keystore it finds. This triggers an interactive UI for an installed KDE wallet and probably very likely triggers an interactive UI (unlock or create keystore) for any other option, too. In the worst case I could be confronted with a whole set of _Unlock password_ dialogs every time jaroco is triggered.
3. During the interactive dialog I have no way to tell "Never try this again!"

A few more thoughts:

* Yesterday I got a similar effect in another application, too. This time it was a Java-based application (_Jetbrains Toolbox_) which started to act similar after a new update.
* Very annoyed i started to uninstall everything even closely remote to KDE wallet: `libkf5wallet-bin libkf5wallet-data libkf5wallet5 libkwalletbackend5-5`. This fixed the effect for the _Toolbox_ app, too. And probably I could remove my previous workaround for problem 2) but not due to problem 1)
* I assume _Back-in_Time_  is only one example of a client which typically operates in a non-interactive way. Though I have the workaround enabled an interactive mode now works flawlessy, my cron backup jobs started each to spill a new warning: `WARNING: import keyring failed`. I'm not sure where this now comes from but maybe the `ChainerBackend` comes into play there due to headless/session-less environment?

> Can you confirm that the user and service you're supplying would return None in the SecretService?

No – nothing has changed there. But honestly things started to act weird and after hard-coding to use the `SecretService` I had to re-enter all my previously entered credentials again. 

On opening seahorse now I see a _huuuuuge_ set of keystores I never saw before:
![grafik](https://user-images.githubusercontent.com/588260/59967546-dcad7b80-952b-11e9-8a8c-e4af875b41c0.png)

> When I originally accepted the Chainer behavior, I was tempted to make it opt-in, but @zooba convinced me to make it enabled by default, providing a nice experience for environments where multiple backends are expected to be meaningful and valuable. 

From my perspective rather the opposite is the case: In which cases do you have multiple meaningful backend ever to the user? And moreover: Why should the way to search for the appropriate key store for a client application ever change? On the other hand – as far as i experienced – suddenly accessing the wrong keystore – even if eventually would reach the right keystore at the end which it doesn't for me – is a rather confusing experience: Unlocking and/or creating more than one UI.

IMHO the implementation should have a solid guess about the most appropriate backend and stick to it as far as possible and maybe offer users an opt-in option to switch the backend i.e. within a preferences dialog (Store your credentials in: [Desktop Default / Gnome / Kwallet / ...]

> Some of the current behaviors I wish to retain:
> *    Keyring should continue to detect all viable backends and select the best one for an environment.

IMHO the application developer should be able to explicitly say:
1. Pick the best one on your own or
2.  Let me pick it on my own.

> I can imagine a few ways to address the situation [...]  what's your instinct about what should be done?

IMHO the process should be 

1. the process should be  _very stable_ in the way it picks a target backend. If it once has identified and picked i.e. SecretStorage as most appropriate backend it should stick to that for eternity even if I start installing KDE apps or hit cancel/entered the wrong passcode on a first UI prompt on someday. I would go that far, that after first success it could store a preference file which ensures that the discovery process wont run again.
2. the process should be  should try to achieve a "just works" with zero configuration

Let's take the following fictitious situation: I have Gnome shell installed. My client application stores 2 credentials. Then I install some KDE-based app which pulls as dependency KWallet. Somehow this changes the order of Chainer and Chainer stores 3 new credentials in KWallet: Now I have 2 in Seahorse and 3 in Kwallet. Everytime I start the client application I need to unlock either the one or the other keystore depending on something which as a user I won't be able to understand.

IMHO something plain and stupid like: User runs in Gome session? Then try and stick to Gnome keystore unless something very very grave hinders us (i.e. it is not even installed) would be better.

>   Keyring should continue to allow multiple backends to serve a query.

As described above I do not know about the usecase behind this requirement but rather see the issues with problematic backends. 

Can you elaborate an example for this requirement? Why should _one_ request be dispatched to multiple backends?

**Comment by jaraco** [comment] 2020-04-30 21:43
> Can you elaborate an example for this requirement? Why should one request be dispatched to multiple backends?

I don't recall the specifics. It was in #352 that functionality was added. I've reached out to the author there to request that information.

> the process should be very stable in the way it picks a target backend

I was inclined to agree, until I think of some of the use-cases where a user has variable demands on the system:

- user has different environments with different backends plugged in.
- user runs with the wrong environment (plugins, backends), then updates to the preferred environment but is stuck on the wrong one.
- one-off invocations that override some setting

Adding state to the system (beyond the state that environments inherently create) vastly complicates the scenarios that can be encountered. The aim of keyring is to provide the best experience for the current environment and provide hooks for the user to override.

So I'll be reluctant to add this complexity to the system without a very compelling use-case. Thusfar, I'm struggling to find that case.

> Why should the way to search for the appropriate key store for a client application ever change?

Consider the simple case where a user started out by storing secrets in a plaintext file, but then decided to start using a more secure methodology. They want to continue to add passwords to the more secure backend but retrieve passwords from the old mechanism. Or maybe they upgraded from kwallet 4 to kwallet 5 and want to use a new backend to access the migrated data. Or maybe they added an extra keystore backed by a third-party backend from which they wish to draw secrets, but also wish to continue to draw secrets from the preferred store.

You said Back-in_Time does something similar. I don't understand the conflicts/interactions with that system. Can you provide some references on what it's doing?

**Comment by bentolor** [comment] 2020-05-04 12:27
From a UX perspective:

I wouldn't mind accessing multiple backends unless this doesn't suprise me as a user i.e. by accessing the KDE wallet (just because the libs are present on the system) which was never used by me and hence
*  prompting a modal, repeatingly opening dialog in an interactive session 
* or simply block/fails in non-interactive sessions

But I'm not sure if this is caused by the [discovery code fragment of Back-in-time](https://github.com/bit-team/backintime/blob/012d9783e966c6744ab30ce6abd299206a324473/common/tools.py#L796) which is now failing on `ChainerBackend`.

My current understanding is that either
* the semantics of keyring API has changed or
* the BIT author misinterpreted the API in the first place an the mentioned code just did not age well

As a workaround I had to deal with the rather esoteric configuration to fix the behavior of keyring as third party library.  I was only capable to do this because I'm having a developer background.  This is, what I find the most troublesome.

The core problem for sure is just the broad diversity of solutions available in Linux desktop environments for core tasks like "secure password storage".

> You said Back-in_Time does something similar. I don't understand the conflicts/interactions with that system. Can you provide some references on what it's doing?

[Please see the source reference in my first ticket:](https://github.com/bit-team/backintime/blob/012d9783e966c6744ab30ce6abd299206a324473/common/tools.py#L796) 

I interpret the code there as Back-in-time is trying to access a keystore backend and if that does not provide any exception adds it to the backends. As far as I understood the change now it should "just rely on keyring to figure out the details"?

> >    Why should the way to search for the appropriate key store for a client application ever change?

> Consider the simple case where a user started out by storing secrets in a plaintext file, but then decided to start using a more secure methodology. 

I'm not sure if a transparent handling of this case would be helpful at all and is worth the pain caused by not having a rather stoic backend selection scheme. At best, my opinion would be, that the user can allow this by behavior by configuration.  

But in most cases I'd expect that keyring should just stick to the default keystore of my desktop environment. Otherwise my new passwords could i.e. saved in a non-secure keystore like you plaintextfile without me as a user being aware of this.

Overall I must say that this really is a very difficult design descision and I feel its rather difficult to get the "right" solution.

Can you have a look at the cited back-in-time source code. Does it make sense for you? If not, how should it be handled properly in your opinion?

**Comment by jaraco** [comment] 2020-05-07 16:30
Thanks for the patient explanation. I think I understand the issue now.

It looks like BIT is not actually doing any special discovery, but is in fact just deferring to keyring for its normal discovery, but adding a check for allowlisted backends.

There's a supported mechanism for BIT to do what it's trying to do, and that's to define a `limit` function to be used during [init_backend](https://github.com/jaraco/keyring/blob/fb74a37d54657b279c76360cf82b850ba33d1654/keyring/core.py#L81-L100). That function is called implicitly on import, but it can be called again by the consumer to override the behavior.

I recommend that BIT adapt their `keyringSupported` function to take a parameter `backend` and return `True` or `False` if that backend is supported. Then invoke `keyring.core.init_backend(limit=keyringSupported)` (or similar). Then, only the allowlisted backends will ever be considered. If the `fail.Keyring` is indicated, that indicates that no matching keyring was indicated.

This feature was added in `keyring 7.3` so that's the minimum version required, but note that 16.0 introduced the Chainer backend and it wasn't until 17.1 that the `limit` parameter was honored in the chainer, so you'll want to use `keyring >= 7.3, != 16, != 16.0.1, != 16.0.2, != 16.1.0, != 16.1.1, != 17` or maybe just require `keyring >= 17.1`.

**Comment by bentolor** [comment] 2020-05-08 06:50
Thanks for you feedback, @jaraco : Unfortunately I'm to far away to fully understand your proposal and if this would solve the b-i-t issue, but I cited you comment and hope that maybe it gets some attention.

Unfortunately back-in-time did not see that much development activity, so that i.e. Fedora is looking for own ways to provide a workaround.

**Comment by jaraco** [comment] 2020-12-22 19:37
Given that the prescribed action is with back-in-time, I'm going to close this issue, but happy to revisit if there's something keyring can do to support better that environment.

**Closed as completed by jaraco** 2020-12-22 19:37 UTC

**Comment by MestreLion** [comment] 2021-02-05 08:28
> The SecretService keyring will be queried first, but if it's a miss (no password defined), the kwallet backend(s) will be queried, triggering the wallet creation UI. I believe the SecretService store is being queried first, but just not satisfying the operation. [...]
> In some ways, the behavior you describe is by design. But you've stumbled on a flaw in the design. [...]
> [...] Where a backend triggers blocking UI elements and [raises KeyringLocked exceptions](https://github.com/jaraco/keyring/blob/a65aa2ea949e78f67dc03abc4bfd4a691bdf0802/keyring/backends/kwallet.py#L101), however, that's not desirable.

My scenario is the same described by the OP, including _exactly_ the same set of backends and priorities: Gnome user, kwallet installed but never used (possibly pulled as a dependency of some other software), on first run (i.e, when trying to read data that was not yet set) it triggers a KDE Wallet Creating UI.

I realize that after some data is set (possibly to Gnome Keyring, given my backend priorities) the KDE UI will not show anymore. But still, this first-time UI is _very_ annoying and surprising.

What's the current status on this? I mean, what should I do, as a third-party developer, to prevent this from happening with my end-users? Is there any "official" (or "blessed") workaround?

A possible approach I'm thinking for my specific software is to try to detect a first-time usage by other means (a missing config file, for example) and the set the data to a dummy/blank value before attempting to read it. That, I _think_, would avoid triggering the "backend found but no data set, let's try another backend" behavior.

Is this a good approach? Any recommendations?

**Comment by jaraco** [comment] 2021-03-05 21:15
This issue is entangled with the back-in-time interaction. Let's address the concern about backend selection between KWallet and Gnome in a separate issue..
