### ISSUE TITLE
SecretService backend does not unlock individual items

### ISSUE THREAD

**Issue by mathstuf** [jaraco/keyring#161] opened 2015-04-09 06:05 UTC
The SecretService spec states that the service may lock individual items separately from the collection. Looking at secretstorage, it seems it does not expose unlocking specific items; filing an issue with it as well.

**Comment by mathstuf** [comment] 2015-04-09 06:09
See mitya57/secretstorage#3

**Comment by mitya57** [comment] 2016-01-09 10:19
SecretStorage now supports an [unlock method](http://pythonhosted.org/SecretStorage/item.html#secretstorage.item.Item.unlock) on Item objects. However, in practice, unlocking an item is the same as unlocking the collection it is stored in. All Python-Keyring items are stored in the default collection, so I don't see any sense in unlocking the items individually.

**Comment by jaraco** [comment] 2016-01-09 10:21
Sounds like a wontfix, but do comment if that's not right.

**Closed as completed by jaraco** 2016-01-09 10:21 UTC
Labels: enhancement

**Comment by mathstuf** [comment] 2016-04-04 14:52
Since there is now the method, I think something like this might work:

``` python
if hasattr(item, 'unlock'):
    if item.is_locked() and not item.unlock():
        raise InitError('failed to unlock the item')
```

This should be backwards compatible and since most implementations lock at the collection level, items shouldn't be locked if the collection is unlocked.

**Comment by mitya57** [comment] 2016-04-04 15:01
`item.unlock()` returns a (`dismissed` (bool), `unlocked` (list)) tuple. So you need to use something like `if item.unlock()[0]:` instead.

If you submit a pull request for this, it will be nice. Though, as I said above, the issue is mostly aesthetic and won't change behavior.
