### ISSUE TITLE
Keyring does not work with PyInstaller

### ISSUE THREAD

**Issue by toyg** [jaraco/keyring#415] opened 2019-12-08 23:41 UTC
All details are in the sister bug at https://github.com/pyinstaller/pyinstaller/issues/4569

Filing here as well because I think the hook they shipped was provided by you...? The hook is executed but somehow the `keyring.backends` module still does not appear in metadata.

**Comment by jaraco** [comment] 2019-12-24 15:22
This is a duplicate of #324.

**Closed as completed by jaraco** 2019-12-24 15:22 UTC
Labels: duplicate
